// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdA1SEvJ4n-kh52XGy1vwT_Is_v0p_ui8',
    appId: '1:380475810278:web:606e3f2aecc86f9ccbf627',
    messagingSenderId: '380475810278',
    projectId: 'meraki-a6d7e',
    authDomain: 'meraki-a6d7e.firebaseapp.com',
    storageBucket: 'meraki-a6d7e.appspot.com',
    measurementId: 'G-J6098369TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD72aXu94pnLi4Tkv4WnAUxtlxi0fSfKU8',
    appId: '1:380475810278:android:582fcdd2175d77f7cbf627',
    messagingSenderId: '380475810278',
    projectId: 'meraki-a6d7e',
    storageBucket: 'meraki-a6d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInVNghAMFPfwa8QgQDBNN7pnOUQqnXvg',
    appId: '1:380475810278:ios:21823a5270e8f289cbf627',
    messagingSenderId: '380475810278',
    projectId: 'meraki-a6d7e',
    storageBucket: 'meraki-a6d7e.appspot.com',
    iosClientId: '380475810278-8gmjedd2kulpa3l6htegigaehh3bctkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.meraki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInVNghAMFPfwa8QgQDBNN7pnOUQqnXvg',
    appId: '1:380475810278:ios:0199408ddbe222c5cbf627',
    messagingSenderId: '380475810278',
    projectId: 'meraki-a6d7e',
    storageBucket: 'meraki-a6d7e.appspot.com',
    iosClientId: '380475810278-sn4v34ba1pegquf2i3fm776kb376h552.apps.googleusercontent.com',
    iosBundleId: 'com.example.meraki.RunnerTests',
  );
}
